# Generated by Django 3.1.7 on 2021-04-10 16:27

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("description", models.CharField(blank=True, max_length=30, null=True, verbose_name="Description")),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("resume", models.TextField(blank=True, max_length=500, null=True, verbose_name="Resume")),
                (
                    "enrollment_type",
                    models.CharField(
                        choices=[("MTR", "Mentor"), ("MTE", "Mentee")],
                        default="MTE",
                        max_length=3,
                        verbose_name="Enrollment type",
                    ),
                ),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[("SE", "Sent"), ("AW", "Awaiting"), ("ON", "Ongoing"), ("FI", "Finished")],
                        default="SE",
                        max_length=2,
                        verbose_name="Enrollment status",
                    ),
                ),
                (
                    "enrollee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enrolle account",
                    ),
                ),
                ("interests", models.ManyToManyField(to="enrollments.Interest")),
                (
                    "matches",
                    models.ManyToManyField(
                        blank=True, related_name="_enrollment_matches_+", to="enrollments.Enrollment"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
