# Generated by Django 3.1.7 on 2021-05-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity', verbose_name='Tasks'),
        ),
    ]
