# Generated by Django 3.1.7 on 2021-05-06 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0003_auto_20210506_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='activities.Comment', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='task',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='activities.activity', verbose_name='Activity'),
        ),
    ]
