# Generated by Django 3.1.7 on 2021-05-06 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20210506_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='activities.activity', verbose_name='Activity'),
        ),
    ]
