# Generated by Django 3.1.7 on 2021-05-06 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0005_auto_20210506_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='activities.activity', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='task',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='activities.activity', verbose_name='Activity'),
        ),
    ]
