# Generated by Django 3.1.7 on 2021-05-06 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_remove_enrollment_matches'),
        ('activities', '0006_auto_20210506_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='enrollments.enrollment', verbose_name='Enrollment'),
        ),
    ]
