# Generated by Django 3.1.7 on 2021-05-06 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0001_initial'),
        ('activities', '0007_activity_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='activity',
            name='mentorship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='mentorships.mentorship', verbose_name='Mentorship'),
        ),
    ]
