# Generated by Django 3.1.7 on 2021-04-13 11:41

import django.db.models.deletion

from django.db import migrations, models

import krenak_api.apps.mentorships.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrollments", "0002_remove_enrollment_matches"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mentorship",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("expiration_date", models.DateTimeField(default=krenak_api.apps.mentorships.models.get_deadline)),
                (
                    "mentee_enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_mentorships",
                        to="enrollments.enrollment",
                    ),
                ),
                (
                    "mentor_enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_mentorships",
                        to="enrollments.enrollment",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("description", models.CharField(max_length=400)),
                ("accomplished_at", models.DateTimeField()),
                (
                    "mentorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="goals", to="mentorships.mentorship"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
